Global:
  Symbol: '!'
  Template: "%prefix%%username%%suffix% &6: %message%"
  Color: "&6"
Local:
  Template: "%prefix%%username%%suffix% : %message%"
  Color: "&f"
Admin:
  Symbol: '\'
  Template: "%prefix%%username%%suffix% &c: %message%"
  Color: "&c"